import Head from 'next/head'
import Link from 'next/link'
import React, { Children } from 'react'

const Layout = ({title, Children }) => {
    return (
        <>
            <Head>
                <title>{title ? title +'-CupCake': 'CupCake'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex min-h-screen flex-col justify-between'>
                <header>
                    <nav className='flex h-12 items-center px-4 justify-between shadow-md'>
                        <Link href="/">
                            <a href="" className="text-lg font-bold">CupCake</a>
                        </Link>
                    <div>
                        <Link href="/cart"><a className="p-2 font-bold">Cart</a></Link>
                        <Link href="/login"><a className="p-2 font-bold">Login</a></Link>
                    </div>
                    </nav>
                </header>
            <main className='container m-auto mt-4 px-4'>
                {Children}
            </main>
            <footer className='flex h-10 justify-center items-center shadow-inner font-bold'>
                <p>Coppyright K 2022 CupCake</p>
            </footer>
            </div>
        </>
    )
}

export default Layout